# Generated by Django 5.1.1 on 2024-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("about", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("fans_count", models.IntegerField(default=0)),
                ("works", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ratings_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("text_reviews_count", models.IntegerField(default=0)),
                ("work_ids", models.CharField(max_length=255)),
                ("book_ids", models.CharField(max_length=255)),
                ("works_count", models.IntegerField(default=1)),
                ("authors", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
